language: java
jdk: oraclejdk8
# git strips the wrapper jar file so we have to force its download during the build
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: VBToFClF7qhIsJBFIhlNHlRDs9qJDL2tPRUm3OtwNI90488FfBSggRNHB4RzayNgfYS6H1VekrEQW/2T/z6Hz2HLUSfP3qC2i6yD+M6sPNsT7wwy7+NQalnEMocF2U9KeeL9VaEVPfIKfLmB/5GTDuHidwj4UpREcj7ojMcfgYoinmmOLg7tvHnAOLH39+XtwZDtryNJW9vCzJjokS+lbq5A8aw4pkAnkJ30Vq3Xp6E76qHQV8sQKOGlOg3gZ95mKC2cwPpWXKy5oRuzXcJC++Dl+fIH9mtxHszbqQIy1sUBHy966nBPu10Gqn1CkZ5jEu3z1d83ZK4X/Divsp/2A40jvJDxeo6D+lWxphvwIJL+E7VDnlGNWHDesTxDKUIo8i3FbyKfOng+gtNZVrc6ay0fUg/OQg0xOOoWJLhFJrhfN0oEJmDQ9EZSKDyvbYgr+7E9jV9F1L5v5gZcxKDoXuO+vLDYDq4+5YxjP2iUyF+kaivydunxIqh2ddpVwlNH6KU827yy5HJUhwliz13nqjbMhe+LA7yMRnAx4yzoSB3jzvmOniYGEw4vepyf0BsKfjqXma+6TL9EoH4vx8wNHgHOGhs17WNRtsYL8GuuBNQBf/rPTEd9bIKUO8yMwqzyhEKaeVNcbgGLB0sGLWJq1Q4GS2CrHg98rJIA6RCVoj8=
  app: ntou-sfd
  on:
    repo: NTOUFoodDelivery/SFD
  run: 'web: java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT
    target/*.war'
