language: java
jdk: oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
#script: mvn test
cache:
  directories:
  - "$HOME/.m2"
before_deploy:
  - mkdir SFD
  - cd SFD
deploy:
  provider: heroku
  api_key:
    secure: OLIiEgoYOcjjKUYov7bmEMc1g8AInkNkh9izol3l14OhOTuNrovFtSuRYPQEW1EvEj3bHHkWgN5Fcet1BhNeWLCUChGETxBGzTXSkkb4QQwG/FBi4wcviwgqFi+DNRhhbxjKy0fJeAyn+8ATWZXLxXSRjhZ3bzeJoOIhitoXSXZssnUuKZu2KXIYiZDKzrIdZDmXstzVuo+xL7xieXmrM6/RmtV0DjTxPf6jFt/D4HqbB0IZnf203ybmEytsBUpO9O02o7NN5xrE2Lkjmw4u8okFHwU9iJz1PXMLYTJjAlZIq3/ytz9nS3R0uPolCYYyZlw2WQAFrGNleggKShAfnzbjUMdyZAE023UJKcHakCA79T1R2HEWaZR33qQXtsNhv0UHF2+ZjuGGkarvcQ9+LIfKDSytp9dho+iSLQw4zqgbeH2OwDtKX1fFO1oXsflOl62qk/vtBJHBPZXpEC7Se3t0E3gTjP5aoEc3FKaO0e9PwMz2yXfyyCk9FhfaJbZlFY0WOo2gLN0vA3YKBu92FmggTCbu0hngZhfqXzKebarmy5mQbhaq7UydfWo+wz5z8Ak6O4KweDFzUoxntL3T/b2EBZw6CWoPewfgvtbLd0hgUzzsK6Vm6Ba1EbRU8BYAwfYlbVugsYzXIVLaY3B35ajWA+X8Gj3cuBC1NDx5xm8=
  app: ntou-sfd
  on:
    repo: NTOUFoodDelivery/SFD
